### ISSUE TITLE
Needless comments in the layouts/_html.view.php

### ISSUE THREAD

**Issue by Mevrael** [Polupanova/MOOD-PHP#7]
You don't have anymore a one big HTML file, thus, such comments are not needed. That is one of the PHP (HTTP/HTML preprocessor) purposes.

There are a lot of extra comments, why do you even need to wrap each single line of `include()` with those comments? Also in PHP template engines it is better to use PHP comments, so the output would be smaller, user don't need all those comments in his final HTML response, however, in this case you don't need comments at all, you already have a **maintainable** structure with a many PHP files.

```html

    <!-- header-Start -->
    
    <?php include '../view/header.view.php' ?>

    <!-- header-end-->
```

**Comment by Polupanova** [comment]
comments have been deleted
